name: jump-scope-analysis
channels:
- conda-forge
dependencies:
- python=3.8
- pip
- pip:
  - numpy=1.22.4
  - pandas=1.4.2
  - matplotlib=3.5.2
  - git+https://github.com/cytomining/pycytominer@36241269c4293c24484986568ca16b2d7eb9e808
  - git+https://github.com/cytomining/cytominer-eval@3c907eaa56a607043a1cb19e0a4d700c79e47c7e
